#地图格式是使用yaml格式还是使用txt好呢
#约定：地图x,y都是非0的
MapConfig:
    map_size: 2000,2000
    #障碍物区域，按：障碍物正中心所在的x,障碍物正中心所在的y,障碍物总长，障碍物总宽 格式存储
    #例如一个长50px，宽20px的长方体障碍物，其正中心在(200,300)处
    #则障碍物区域为x:[200-25, 200+25]，y:[300-10, 300+10]
    #存储格式为:200,300,50,20
    block_area:
        - block_1: 200,300,50,20
        - block_2: 500,200,34,28

    